export type Project = {
  id: string;
  slug: string;
  number: string;
  title: string;
  client: string;
  year: string;
  type: string;
  summary: string;
  image: string;
  featured: boolean;
  ai?: boolean;
};

const CDN = "https://storage.googleapis.com/2026portfolio/Projects";

export const projects: Project[] = [
  {
    id: "01",
    slug: "iris-v3",
    number: "01",
    title: "IRIS V3",
    client: "NETZSCH",
    year: "2024",
    type: "Industrial SaaS",
    summary:
      "End-to-end UX strategy for a global industrial HMI platform. Reduced onboarding by ~40% through task-oriented workflows.",
    image: `${CDN}/IRIS/IRIS_Cover.png`,
    featured: true,
  },
  {
    id: "02",
    slug: "netzsch-design-system",
    number: "02",
    title: "NETZSCH Design System",
    client: "NETZSCH",
    year: "2023",
    type: "Design System",
    summary:
      "Built and governed a global design system in Figma + React/Storybook. Adopted across multiple product teams.",
    image: `${CDN}/NETZSCH%20Design%20System/DS_Cover.png`,
    featured: true,
  },
  {
    id: "03",
    slug: "myct-connecticut",
    number: "03",
    title: "MyCT",
    client: "Connecticut.gov",
    year: "2022",
    type: "Public-sector Platform",
    summary:
      "Citizen-facing government portal. WCAG 2.1 AA, plain language at 8th grade level, mobile-first.",
    image: `${CDN}/MyCT%20Connecticut/ct_cover.png`,
    featured: true,
  },
  {
    id: "04",
    slug: "netzsch-customer-portal",
    number: "04",
    title: "Customer Portal",
    client: "NETZSCH",
    year: "2023",
    type: "B2B E-commerce",
    summary:
      "Industrial e-commerce on Salesforce + SAP. Increased self-service and reduced support load.",
    image: `${CDN}/Customer%20Portal/cp_thumb.png`,
    featured: true,
  },
  {
    id: "05",
    slug: "iris-design-system",
    number: "05",
    title: "IRIS Design System",
    client: "NETZSCH",
    year: "2024",
    type: "Design System",
    summary:
      "Pragmatic modular DS for industrial software, built within proprietary framework constraints.",
    image: `${CDN}/IRIS%20Design%20System/iris_ds_thumb.png`,
    featured: false,
  },
  {
    id: "06",
    slug: "techcolab",
    number: "06",
    title: "TechCo.lab",
    client: "TechCo.lab",
    year: "2024",
    type: "Landing Page · AI workflow",
    summary:
      "Designer-owned full stack — concept to live URL without devs, using Figma Make + vibe coding.",
    image: `${CDN}/Techco.lab%20Landing%20Page/tcl_thumb.png`,
    featured: true,
    ai: true,
  },
  {
    id: "07",
    slug: "voa-clinic",
    number: "07",
    title: "VOA Clinic",
    client: "VOA Digital",
    year: "2025",
    type: "SaaS · AI-built",
    summary:
      "Multi-tenant SaaS for clinical practices. Designed and shipped end-to-end with Claude Code as the build partner.",
    image: `${CDN}/Customer%20Portal/cp_thumb.png`,
    featured: true,
    ai: true,
  },
  {
    id: "08",
    slug: "garmin-coach",
    number: "08",
    title: "Garmin Coach",
    client: "Side project",
    year: "2025",
    type: "AI-native CLI + Web",
    summary:
      "JSON-driven training plans generated by an LLM, pushed straight into Garmin Connect.",
    image: `${CDN}/Customer%20Portal/cp_thumb.png`,
    featured: true,
    ai: true,
  },
  {
    id: "09",
    slug: "voa-portal",
    number: "09",
    title: "VOA Portal",
    client: "VOA Digital",
    year: "2025",
    type: "Internal SaaS · AI workflow",
    summary:
      "The operating system that runs my agency: pipeline, briefing, finance, scraping. Built and shipped solo.",
    image: `${CDN}/Customer%20Portal/cp_thumb.png`,
    featured: false,
    ai: true,
  },
  {
    id: "10",
    slug: "ortolink",
    number: "10",
    title: "Ortolink",
    client: "Rotary Club (pro-bono)",
    year: "2021",
    type: "Mobile App",
    summary:
      "Solo product design for medical equipment lending — community impact at neighborhood scale.",
    image: `${CDN}/Ortolink/orto_cover.png`,
    featured: false,
  },
  {
    id: "11",
    slug: "superdigital",
    number: "11",
    title: "SuperDigital",
    client: "Santander",
    year: "2019",
    type: "Mobile Banking",
    summary: "Fintech platform serving millions across Latin America.",
    image: `${CDN}/SuperDigital/super_thumb.png`,
    featured: false,
  },
  {
    id: "12",
    slug: "dell-expert-network",
    number: "12",
    title: "Dell Expert Network",
    client: "Dell",
    year: "2018",
    type: "Enterprise Education",
    summary: "Certification and education platform for Dell's enterprise partners.",
    image: `${CDN}/Dell/dell_thumb.png`,
    featured: false,
  },
  {
    id: "13",
    slug: "eye",
    number: "13",
    title: "EYE",
    client: "Indie",
    year: "2017",
    type: "Game · Narrative TPS",
    summary: "Third-person shooter with narrative-led mechanics. Solo design role.",
    image: `${CDN}/EYE/eye_thumb.png`,
    featured: false,
  },
  {
    id: "14",
    slug: "gan-dath",
    number: "14",
    title: "Gan Dath",
    client: "Indie",
    year: "2016",
    type: "Game · Experimental 3D",
    summary: "Experimental 3D game exploring gravity-driven mechanics.",
    image: `${CDN}/GanDath/gd_thumb.png`,
    featured: false,
  },
];

export const featured = projects.filter((p) => p.featured);
export const archive = projects.filter((p) => !p.featured);
