export type Project = {
  id: string;
  slug: string;
  number: string;
  title: string;
  client: string;
  year: string;
  type: string;
  summary: string;
  image?: string;
  gradient?: string;
  featured: boolean;
  ai?: boolean;
  metric?: { label: string; value: string };
  size?: "wide" | "tall" | "normal" | "feature";
  personal?: boolean;
};

const CDN = "https://storage.googleapis.com/2026portfolio/Projects";

export const projects: Project[] = [
  {
    id: "01",
    slug: "iris-v3",
    number: "01",
    title: "IRIS V3",
    client: "NETZSCH",
    year: "2023→",
    type: "Industrial HMI Platform",
    summary:
      "Sole UX designer on NETZSCH's global HMI platform. 6 product lines, one design system, 35 months and counting.",
    image: `${CDN}/IRIS/IRIS_Cover.png`,
    featured: true,
    metric: { label: "Product lines unified", value: "6" },
    size: "wide",
  },
  {
    id: "02",
    slug: "netzsch-design-system",
    number: "02",
    title: "DAS Design System",
    client: "NETZSCH · Digital and Automation Systems",
    year: "2023",
    type: "Design System",
    summary:
      "Built and governed DASDS — the design system for NETZSCH's Digital and Automation Systems. Figma + React/Storybook, adopted across squads.",
    image: "/projects/dasds/00__dasds-cover.png",
    featured: true,
    metric: { label: "Product teams", value: "8+" },
    size: "normal",
  },
  {
    id: "03",
    slug: "myct-connecticut",
    number: "03",
    title: "MyCT",
    client: "Connecticut.gov",
    year: "2022",
    type: "Public-sector Platform",
    summary: "Citizen-facing portal. WCAG 2.1 AA, plain language, mobile-first.",
    image: `${CDN}/MyCT%20Connecticut/ct_cover.png`,
    featured: true,
    size: "tall",
  },
  {
    id: "04",
    slug: "nerida",
    number: "04",
    title: "Nerida",
    client: "Solo founder",
    year: "2025→",
    type: "Modular health SaaS · AI-built",
    summary:
      "Modular platform for solo health professionals in Brazil. Psychologists in production, nutritionists in beta. Designed, built, and operated solo.",
    image: "/projects/nerida/00__lp-hero.png",
    featured: true,
    ai: true,
    metric: { label: "Active clients", value: "100+" },
    size: "normal",
  },
  {
    id: "15",
    slug: "norius",
    number: "15",
    title: "Norius",
    client: "NETZSCH do Brasil · Techco.lab",
    year: "2026",
    type: "IoT Platform · Design System",
    summary:
      "Redesign of an industrial IoT monitoring platform, from discovery to Storybook. 30 components, 155 stories, a navigable prototype.",
    image: "/projects/norius/01__norius-dashboard.png",
    featured: true,
    metric: { label: "Components in Storybook", value: "30" },
    size: "normal",
  },
  {
    id: "05",
    slug: "garmin-coach",
    number: "05",
    title: "Garmin Coach",
    client: "Side project · OSS",
    year: "2025→",
    type: "AI-native CLI + Web",
    summary:
      "JSON-driven training plans generated by an LLM, pushed straight into Garmin Connect.",
    image: "/projects/garmin-cover.png",
    featured: false,
    ai: true,
    personal: true,
    size: "normal",
  },
  {
    id: "16",
    slug: "mosey",
    number: "16",
    title: "Mosey",
    client: "Solo · Personal",
    year: "2026",
    type: "iOS App · AI on-device",
    summary:
      "A personal travel app for 27 days across Denmark and Norway. Native iOS, anti-itinerary, planning generated by on-device AI.",
    image: "/projects/mosey/00__mosey-cover.png",
    featured: false,
    ai: true,
    personal: true,
    size: "normal",
  },
  {
    id: "06",
    slug: "techcolab",
    number: "06",
    title: "TechCo.lab",
    client: "TechCo.lab",
    year: "2024",
    type: "Landing · AI workflow",
    summary: "Designer-owned full stack. Concept to live URL with Figma Make + vibe coding.",
    image: "/projects/techcolab/01__tcl-hero.png",
    featured: true,
    ai: true,
    size: "wide",
  },
  {
    id: "08",
    slug: "netzsch-customer-portal",
    number: "08",
    title: "Customer Portal",
    client: "NETZSCH · Grinding & Dispersing",
    year: "2025–2026",
    type: "B2B Self-service Portal",
    summary:
      "Self-service portal for industrial customers: machines, spare parts, contracts, and an AI assistant. 110+ frames, 12 flows, 4 roles.",
    image: "/projects/customer-portal/00__cp-dashboard.png",
    featured: false,
    metric: { label: "Flows designed", value: "12" },
  },
  {
    id: "09",
    slug: "iris-design-system",
    number: "09",
    title: "IRIS Design System",
    client: "NETZSCH",
    year: "2023→",
    type: "Design System",
    summary:
      "The component library behind the IRIS HMI platform. 29 component families, tokens, 12\" and 15\" panel variants.",
    image: "/projects/iris-ds/00__irisds-cover.png",
    featured: false,
    metric: { label: "Component families", value: "29" },
  },
  {
    id: "10",
    slug: "ortolink",
    number: "10",
    title: "Ortolink",
    client: "Rotary Club",
    year: "2021",
    type: "Mobile App · pro-bono",
    summary: "Solo design for medical equipment lending.",
    image: `${CDN}/Ortolink/orto_cover.png`,
    featured: false,
  },
  {
    id: "11",
    slug: "superdigital",
    number: "11",
    title: "SuperDigital",
    client: "Santander",
    year: "2019",
    type: "Mobile Banking",
    summary: "Fintech for millions across Latin America.",
    image: `${CDN}/SuperDigital/super_thumb.png`,
    featured: false,
  },
  {
    id: "12",
    slug: "dell-expert-network",
    number: "12",
    title: "Dell Expert Network",
    client: "Dell",
    year: "2018",
    type: "Enterprise Education",
    summary: "Certification platform for Dell's enterprise partners.",
    image: `${CDN}/Dell/dell_thumb.png`,
    featured: false,
  },
  {
    id: "13",
    slug: "eye",
    number: "13",
    title: "EYE",
    client: "Indie",
    year: "2017",
    type: "Game · Narrative TPS",
    summary: "Third-person shooter with narrative-led mechanics.",
    image: `${CDN}/EYE/eye_thumb.png`,
    featured: false,
  },
  {
    id: "14",
    slug: "gan-dath",
    number: "14",
    title: "Gan Dath",
    client: "Indie",
    year: "2016",
    type: "Game · Experimental 3D",
    summary: "Experimental 3D game exploring gravity-driven mechanics.",
    image: `${CDN}/GanDath/gd_thumb.png`,
    featured: false,
  },
];

export const featured = projects.filter((p) => p.featured);
export const personal = projects.filter((p) => p.personal);
export const archive = projects.filter((p) => !p.featured && !p.personal);
