// Lightweight project list for the /testeN landing variants.
// Curated to 6 — what a recruiter will see in the first scan.

export type LightProject = {
  number: string;
  slug: string;
  title: string;
  client: string;
  year: string;
  type: string;
  oneLiner: string;
  metric?: string;
  ai?: boolean;
  image?: string;
  gradient?: string;
};

const CDN = "https://storage.googleapis.com/2026portfolio/Projects";

export const lightProjects: LightProject[] = [
  {
    number: "01",
    slug: "iris-v3",
    title: "IRIS V3",
    client: "NETZSCH",
    year: "2024",
    type: "Industrial SaaS",
    oneLiner: "End-to-end UX strategy for a global industrial HMI platform.",
    metric: "Onboarding −40%",
    image: `${CDN}/IRIS/IRIS_Cover.png`,
  },
  {
    number: "02",
    slug: "netzsch-design-system",
    title: "NETZSCH Design System",
    client: "NETZSCH",
    year: "2023",
    type: "Design System",
    oneLiner: "Built and governed a global DS adopted across 8+ product teams.",
    metric: "8+ teams",
    image: `${CDN}/NETZSCH%20Design%20System/DS_Cover.png`,
  },
  {
    number: "03",
    slug: "myct",
    title: "MyCT",
    client: "Connecticut.gov",
    year: "2022",
    type: "Public-sector",
    oneLiner: "Citizen-facing portal — WCAG 2.1 AA, plain language, mobile-first.",
    image: `${CDN}/MyCT%20Connecticut/ct_cover.png`,
  },
  {
    number: "04",
    slug: "nerida",
    title: "Nerida",
    client: "Solo founder",
    year: "2025",
    type: "AI-built SaaS",
    oneLiner: "A focused SaaS for solo psychologists, designed and shipped end-to-end with Claude Code.",
    metric: "12 weeks",
    ai: true,
    gradient: "linear-gradient(135deg,#1e3a8a 0%,#3b82f6 60%,#93c5fd 100%)",
  },
  {
    number: "05",
    slug: "garmin-coach",
    title: "Garmin Coach",
    client: "Side project · OSS",
    year: "2025",
    type: "AI-native CLI + Web",
    oneLiner: "JSON-driven training plans generated by an LLM, pushed straight into Garmin Connect.",
    ai: true,
    gradient: "linear-gradient(135deg,#0c4a6e 0%,#0891b2 50%,#67e8f9 100%)",
  },
  {
    number: "06",
    slug: "techcolab",
    title: "TechCo.lab",
    client: "TechCo.lab",
    year: "2024",
    type: "Landing · vibe coding",
    oneLiner: "Designer-owned full stack: concept to live URL with Figma Make + AI workflow.",
    ai: true,
    image: `${CDN}/Techco.lab%20Landing%20Page/tcl_thumb.png`,
  },
];
